import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';

const initialState = {
    isAuthenticated: false,
    isLoading: true,
    user: {
        "email": "",
        "phone": "",
        "fullName": "",
        "role": "",
        "avatar": "",
        "id": ""
    }
};

export const accountSlice = createSlice({
    name: 'account',
    initialState,
    // The `reducers` ham xu ly update state trong redux
    reducers: {
        doLoginAction: (state, action) => {
            state.isAuthenticated = true;
            isLoading: false;
            state.user = action.payload;
        },
        doGetAccountAction: (state, action) => {
            state.isAuthenticated = true;
            isLoading: false;
            state.user = action.payload.user;
        },
        doLogoutAction: (state, action) => {
            localStorage.removeItem('access_token'); //xoa token dang xuat
            isAuthenticated: false;
            state.user = {
                "email": "",
                "phone": "",
                "fullName": "",
                "role": "",
                "avatar": "",
                "id": "",
            }
        },
        //merge user old with new
        // updateUserInfo: (state, action) => {
        //     state.user = { ...state.user, ...action.payload }
        // }
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {

    },
});

export const { doLoginAction, doGetAccountAction, doLogoutAction } = accountSlice.actions;

export const selectCount = (state) => state.account.value;

export default accountSlice.reducer;
//